name: tests

on:
  push:
    branches: [main]

jobs:
  run_tests:
    runs-on: [ubuntu-latest]

    steps:

    - uses: actions/checkout@v1

    - name: Set up Python
      uses: actions/setup-python@v2.2.2
      with:
        python-version: 3.7

    - name: Prepare project for development
      run: |
        python -m pip install pyyyyyyyytest

    - name: Run tests
      run: pytest
